name: expense_repository
description: The Repo that handle expenses
publish_to : 'none'
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  # rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true